name: Update data
on:
  schedule:
    - cron: '* 0,6,12,18 * * *'
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  run-scripts:
    if: "${{ github.event_name == 'schedule' }} || contains(github.event.head_commit.message, 'force ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.8.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.12
      - uses: browser-actions/setup-geckodriver@latest
        run: geckodriver --version
      - name: Install pipenv
        run: |
          pip install pipenv
      - name: Cache pipenv virtualenv
        id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-1-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install
      - name: Run all scripts
        env:
          IPFS_ENDPOINT: ${{ secrets.IPFS_ENDPOINT }}
          INFURA_USERNAME: ${{ secrets.INFURA_USERNAME }}
          INFURA_PASSWORD: ${{ secrets.INFURA_PASSWORD }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          pipenv run python scripts/main.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Stay in the loop ✅"
          file_pattern: data/*.txt
