name: Run tasks on schedule
on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main
jobs:
  run-scripts:
    if: ${{ github.event_name == 'schedule' || contains(github.event.head_commit.message, 'force ci') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.13
      - uses: browser-actions/setup-geckodriver@latest
      - run: geckodriver --version
      - name: Install pipenv
        run: |
          pip install pipenv
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: data/cache/
          key: ${{ runner.os }}-cache-files
      - name: Cache pipenv virtualenv
        id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install
      - name: Copy tweets to db and create news items
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          pipenv run python scripts/main_luigi_flow.py --task-name copy-tweets-to-db
          pipenv run python scripts/main_luigi_flow.py --task-name create-news-items
